services:
  - type: web
    name: canadian-contracts-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://canadian-contracts-api.onrender.com/api

  - type: web
    name: canadian-contracts-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: UPLOAD_DIR
        value: uploads
      - key: NODE_ENV
        value: production 