services:
  - type: web
    name: canadian-contracts-api
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node dist/server.js
    envVars:
      - key: PORT
        value: 3001
      - key: UPLOAD_DIR
        value: uploads
      - key: NODE_ENV
        value: production

  - type: static
    name: canadian-contracts-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: canadian-contracts-api
          type: web
          property: url
          envVarKey: VITE_API_URL
        value: ${VITE_API_URL}/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 