services:
  - type: web
    name: canadian-contracts
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DOCKER_COMPOSE_VERSION
        value: "1.29.2"
      - key: VITE_API_URL
        value: https://canadian-contracts-api.onrender.com/api
      - key: PORT
        value: 3001
      - key: UPLOAD_DIR
        value: uploads
      - key: NODE_ENV
        value: production 